### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by javierpastorfernandez** [JMoonr/mmlane#1]
Good morning,

Congrats on your publication! It is truly a brand-new idea and implementation for lane detection.
Do you plan on publishing the code soon?

Yours sincerely,
Javier P.

**Comment by JMoonr** [comment]
We will release the code when our work gets accepted :)

**Comment by JMoonr** [comment]
Thanks for your interest. We will release the code when our work gets accepted :)

**Comment by ppbangKGT** [comment]
> Thanks for your interest. We will release the code when our work gets accepted :)

Thanks for your great work! Have your work been accepted? Looking forward to learning your code.

**Comment by PumpkinCCC** [comment]
> Owner

Thank you for your excellent work!!! Has your work been accepted? Looking forward to learning your code. :)

**Comment by upupbo** [comment]
啥时候开源
